const PURCHASE_TYPE = {
  PURCHASE_TYPE_FULL: 1,
  PURCHASE_TYPE_SIMPLIFIED_CALL: 2,
  PURCHASE_TYPE_SIMPLIFIED_PAYMENT_PAGE: 3
}
const CARD_TOKEN_REQUEST = {
  CARD_TOKEN_REQUEST_NONE: 0,
  CARD_TOKEN_REQUEST_ONLY_STORE: 1,
  CARD_TOKEN_REQUEST_PAY_AND_STORE: 2
}
const PAYMENT_METHOD = {
  PAYMENT_METHOD_STANDARD: 1,
  PAYMENT_METHOD_IDEAL: 2,
  PAYMENT_METHOD_BOTH: 3
}
const PAYMENT_STATUS = {
  PAYMENT_STATUS_SUCCESSFUL: 1,
  PAYMENT_STATUS_PENDING: 2,
  PAYMENT_STATUS_UNSUCCESSFUL: 3
}
const CARD_TYPE = {
  CARD_TYPE_MASTERCARD: 1,
  CARD_TYPE_MAESTRO: 2,
  CARD_TYPE_VISA: 3,
  CARD_TYPE_VISA_ELECTRON: 4,
  CARD_TYPE_VPAY: 5,
  CARD_TYPE_JCB: 6,
  CARD_TYPE_BANCONTACT: 7,
  CARD_TYPE_AMEX: 8
}
const CARD_VERIFICATION = {
  CARD_VERIFICATION_NO: 1,
  CARD_VERIFICATION_YES: 2
}
const MANDATE_MANAGEMENT_ACTION = {
  MANDATE_MANAGEMENT_ACTION_REGISTER: 1,
  MANDATE_MANAGEMENT_ACTION_CANCEL: 2
}
const COMMUNICATION_FORMAT = {
  COMMUNICATION_FORMAT_XML: 'xml',
  COMMUNICATION_FORMAT_JSON: 'json',
  COMMUNICATION_FORMAT_POST: 'post'
}
const STATUS = {  
  STATUS_SUCCESS: 0,
  STATUS_MISSING_REQ_PARAMS: 1,
  STATUS_SIGNATURE_FAILED: 2,
  STATUS_IPC_ERROR: 3,
  STATUS_INVALID_SID: 4,
  STATUS_INVALID_PARAMS: 5,
  STATUS_INVALID_REFERER: 6,
  STATUS_PAYMENT_TRIES: 7,
  STATUS_TRANSACTION_AUTH_FAIL: 8,
  STATUS_WRONG_AMOUNT: 9,
  STATUS_UNSUPPORTED_CALL: 10,
  STATUS_INACTIVE_MANDATE_REFERENCE: 11,
  STATUS_INVALID_MANDATE_REFERENCE: 12,
  STATUS_NOT_SUFFICIENT_FUNDS: 13,
  STATUS_TRANSACTION_NOT_PERMITTED: 14,
  STATUS_EXCEEDED_LIMIT: 15,
  STATUS_MANDATE_ALREADY_REGISTERED: 16,
  STATUS_INACTIVE_ACOUNTIDENTIFIER: 17,
  STATUS_INVALID_ACOUNTIDENTIFIER: 18,
  STATUS_EXCEEDED_ACCOUNT_LIMITS: 19,
  STATUS_DUPLICATE_TRANSMISSION: 20,
  STATUS_TRANSACTION_DECLINED: 21,
  STATUS_UNDEFINED_ERROR: 99
}
module.exports = {
  PURCHASE_TYPE,
  CARD_TOKEN_REQUEST,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  CARD_TYPE,
  CARD_VERIFICATION,
  MANDATE_MANAGEMENT_ACTION,
  COMMUNICATION_FORMAT,
  STATUS
}